# Generated by Django 4.2.13 on 2024-05-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0003_alter_student_options_student_email_ucitel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='popis',
            field=models.TextField(blank=True),
        ),
    ]
