# Generated by Django 4.2.13 on 2024-05-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0004_tema_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='dostupnost',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('IT', 'Italy')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
