# Generated by Django 4.2.13 on 2024-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0005_tema_dostupnost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.CharField(choices=[('Voľne', 'Voľne'), ('Čakajúce', 'Čakajúce'), ('Obsadené', 'Obsadené')], max_length=300),
        ),
    ]
