# Generated by Django 5.0 on 2024-06-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0006_alter_tema_dostupnost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Odbor',
                'verbose_name_plural': 'Odbory',
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='konzultacie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='odbor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.odbor'),
        ),
    ]
