# Generated by Django 5.0 on 2024-06-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0007_odbor_tema_konzultacie_tema_odbor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='konzultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.ucitel'),
        ),
    ]
