# Generated by Django 5.0 on 2024-06-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0009_alter_student_heslo_alter_student_meno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostupnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moznost', models.CharField(choices=[('Voľne', 'Voľne'), ('Čakajúce', 'Čakajúce'), ('Obsadené', 'Obsadené')], max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc.dostupnost'),
        ),
    ]
