# Generated by Django 5.0 on 2024-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0010_dostupnost_alter_tema_dostupnost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostupnost',
            name='moznost',
            field=models.CharField(max_length=50),
        ),
    ]
