# Generated by Django 5.0 on 2024-06-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0011_alter_dostupnost_moznost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.CharField(choices=[('Voľne', 'Voľne'), ('Čakajúce', 'Čakajúce'), ('Obsadené', 'Obsadené')], max_length=300),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nazov',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Dostupnost',
        ),
    ]
