# Generated by Django 5.0 on 2024-06-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0012_alter_tema_dostupnost_alter_tema_nazov_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='odbor',
        ),
    ]
