# Generated by Django 5.0 on 2024-06-12 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0013_remove_student_odbor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='konzultacie',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='ucitel',
            name='titul',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
