# Generated by Django 5.0 on 2024-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0014_alter_tema_konzultacie_alter_ucitel_titul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='nazov',
            field=models.CharField(max_length=60),
        ),
    ]
